load("@io_bazel_rules_scala//scala:scala.bzl", "scala_binary", "scala_library", "scala_test")

scala_binary(
    name = ".",
    srcs = glob(["src/main/scala/**/*.scala"]),
    main_class = "myexamples.Main"
)
