## see https://github.com/bazelbuild/rules_scala#getting-started

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

##############################################################################
## see https://github.com/bazelbuild/bazel-skylib/releases

skylib_version = "1.4.2"
skylib_sha256 = "66ffd9315665bfaafc96b52278f57c7e2dd09f5ede279ea6d39b2be471e7e3aa"

http_archive(
    name = "bazel_skylib",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/bazel-skylib/releases/download/{}/bazel-skylib-{}.tar.gz".format (skylib_version, skylib_version),
        "https://github.com/bazelbuild/bazel-skylib/releases/download/{}/bazel-skylib-{}.tar.gz".format (skylib_version, skylib_version),
    ],
    sha256 = skylib_sha256,
)
load("@bazel_skylib//:workspace.bzl", "bazel_skylib_workspace")
bazel_skylib_workspace()

##############################################################################
## see https://github.com/bazelbuild/rules_scala

rules_scala_version = "6.0.0" # update this as needed
rules_scala_sha256 = "d39aceb39808da3ee5d84f8d6e460be0568e946da71698fc1414fc696765200a"

http_archive(
    name = "io_bazel_rules_scala",
    strip_prefix = "rules_scala-{}".format (rules_scala_version),
    type = "tar.gz",
    url = "https://github.com/bazelbuild/rules_scala/releases/download/v{}/rules_scala-v{}.tar.gz".format (rules_scala_version, rules_scala_version),
    sha256 = rules_scala_sha256,
)

# Stores Scala version and other configuration
# 2.12 is a default version, other versions can be use by passing them explicitly:
# scala_config(scala_version = "2.11.12")
load("@io_bazel_rules_scala//:scala_config.bzl", "scala_config")
scala_config(scala_version = "2.13.6")

load("@io_bazel_rules_scala//scala:scala.bzl", "rules_scala_setup", "scala_repositories")
rules_scala_setup()
scala_repositories()

load("@rules_proto//proto:repositories.bzl", "rules_proto_dependencies", "rules_proto_toolchains")
rules_proto_dependencies()
rules_proto_toolchains()

load("@io_bazel_rules_scala//scala:toolchains.bzl", "scala_register_toolchains")
scala_register_toolchains()

# optional: setup ScalaTest toolchain and dependencies
load("@io_bazel_rules_scala//testing:scalatest.bzl", "scalatest_repositories", "scalatest_toolchain")
scalatest_repositories()
scalatest_toolchain()

##############################################################################
## see https://github.com/protocolbuffers/protobuf/releases

protobuf_version = "3.20.1"
protobuf_sha256 = "36f81e03a0702f8f935fffd5a486dac1c0fc6d4bae1cd02c7a32448ad6e63bcb"

http_archive(
    name = "com_google_protobuf",
    url = "https://github.com/protocolbuffers/protobuf/archive/v%s.tar.gz" % protobuf_version,
    strip_prefix = "protobuf-%s" % protobuf_version,
    sha256 = protobuf_sha256,
)

##############################################################################
## END
